run:
  max_num_steps: 15
  wandb: False
  project_name: eval-test
  baseline_dir: data/baseline_results
  log_path: ${PROJECT_PATH}/results/debug_mpc_sample_agent
# only provide example run_config here, please specify with arguments when running
# --wandb --max_num_steps 30 --project_name ... --baseline_dir ... --log_path ...

agent:
  name: MPCSample
  memory_size: 200
  need_goal: True
  n_gram: 30
  similarity_threshold_low: 0.5
  similarity_threshold_high: 0.7
  reward_threshold: 0.0 # llm - 0.2 # heuristic - 0.6
  do_sample: True
  max_world_model_len: 500
  beam_temperature: 0.7
  select_temperature: 0.005 #.05 # llm 0.3 # heuristic - 0.05, smaller difference than llm
  n_generate_sample: 8
  value_type: llm

llm:
  gpt-35-turbo: # using gpt_azure llm would need azure versin of openai key
      name: gpt_azure
      engine: gpt-35-turbo
      context_length: 4096
      use_azure: True
      temperature: 0.1
      top_p: 0.9
      retry_delays: 20
      max_retry_iters: 15
      stop: 
      use_parser: False
      max_tokens: 200

env:
  alfworld:
    name: alfworld
    base_config: ${PROJECT_PATH}/agentboard/environment/alfworld/base_config.yaml
    split: eval_out_of_distribution
    batch_size: 1
    label_path: ${PROJECT_PATH}/data/alfworld/test.jsonl
    check_inventory: True
    check_actions: check valid actions
    init_prompt_path: ${PROJECT_PATH}/agentboard/prompts/Agent/alfworld_act.json